---
# Shutdown Nodes
ss_bspd:
ss_is:
ss_bots:
ss_estop_driver:
ss_hvd:
ss_hvd_conn:
ss_mpc:
ss_bms:
ss_imd:
ss_tsms:
---
# Vehicle Values
throttle_l_pos:
throttle_r_pos:
throttle_r_out_of_range:
throttle_deviation:
throttle_brake_implaus:
brake_gate:
brake_pressure:
ready_to_drive:
start_button_state:
air_p_status:
air_n_status:
pack_voltage:
pack_current:
max_temperature:
  processing_function: convertVtoT
min_temperature:
  processing_function: convertVtoT
D1_DC_Bus_Voltage:
Torque_Command:
bms_fault_code:
  processing_function: decode_bms_fault_msg
csc_mia:
  processing_function: decode_csc_status
internal_die_temp: convert_internal_die_temp

---
# Vehicle States (state and fault)
air_control_critical:
  air_state:
  air_fault:
bms_core:
  bms_state:
  bms_fault_state:
throttle:
  throttle_status:
