---
# Shutdown Nodes
ss_bspd:
ss_is:
ss_bots:
ss_estop_driver:
ss_hvd:
ss_hvd_conn:
ss_mpc:
ss_bms:
ss_imd:
ss_tsms:
---
# Vehicle Values
throttle_l_pos:
throttle_r_pos:
brake_gate:
ready_to_drive:
air_p_status:
air_n_status:
pack_voltage:
max_temperature:
  # processing_function: convertVtoT
min_temperature:
  # processing_function: convertVtoT
temperature_1:
temperature_2:
D1_DC_Bus_Voltage:
temperature_1:
temperature_2:

Torque_Command:
---
# Vehicle States (state and fault)
air_control_critical:
  air_state:
  air_fault:
bms_core:
  bms_state:
  bms_fault:
throttle:
  throttle_state:
