name: lint

on:
  pull_request:
    paths:
    - **/BUILD*
    - WORKSPACE
    - **/*.bzl

jobs:
  buildifier:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run buildifier
      run: bazelisk run //:buildifier_check
